- name: Set static hostname
  command: hostnamectl set-hostname {{ inventory_hostname_short }} --static

- name: Set Pretty  hostname
  command: 'hostnamectl set-hostname "{{ bootstap_systemdescription }}" --pretty'

- name: Get ip from hostname
  command: dnsdomainname -I
  register: host_ip

- name: Update hosts
  lineinfile: path=/etc/hosts line="{{ host_ip.stdout_lines[0] }} {{ inventory_hostname_short }} {{ inventory_hostname }}"
