---
# tasks file for centos-bootstrap
- name: BOOTSTRAPPING | Spacewalk
  include_tasks: bootstrap.yml
  when: bootstrap_operation == 'bootstrap'
- name: COFIGURE |  Spacewalk Configuring Task
  include_tasks: configure.yml
  when: bootstrap_operation == 'configure'
